export const DEFAULT_MENU = [
  { id: 'ck-half', name: 'Chicken Karahi (Half)', nameUrdu: 'چکن کڑاہی (ہاف)', category: 'Karahi', price: 950 },
  { id: 'ck-full', name: 'Chicken Karahi (Full)', nameUrdu: 'چکن کڑاہی (فل)', category: 'Karahi', price: 1800 },
  { id: 'mk-half', name: 'Mutton Karahi (Half)', nameUrdu: 'مٹن کڑاہی (ہاف)', category: 'Karahi', price: 1450 },
  { id: 'mk-full', name: 'Mutton Karahi (Full)', nameUrdu: 'مٹن کڑاہی (فل)', category: 'Karahi', price: 2700 },
  { id: 'daal', name: 'Daal Fry', nameUrdu: 'دال فرائی', category: 'Karahi', price: 380 },
  { id: 'palak', name: 'Palak Paneer', nameUrdu: 'پالک پنیر', category: 'Karahi', price: 520 },
  { id: 'roti', name: 'Tandoori Roti', nameUrdu: 'تندوری روٹی', category: 'Naan & Roti', price: 25 },
  { id: 'naan', name: 'Roghni Naan', nameUrdu: 'روغنی نان', category: 'Naan & Roti', price: 60 },
  { id: 'garlic', name: 'Garlic Naan', nameUrdu: 'گارلک نان', category: 'Naan & Roti', price: 80 },
  { id: 'seekh', name: 'Seekh Kabab', nameUrdu: 'سیخ کباب', category: 'BBQ', price: 380 },
  { id: 'malai', name: 'Malai Boti', nameUrdu: 'ملائی بوٹی', category: 'BBQ', price: 420 },
  { id: 'biryani', name: 'Chicken Biryani', nameUrdu: 'چکن بریانی', category: 'Rice', price: 380 },
  { id: 'pulao', name: 'Yakhni Pulao', nameUrdu: 'یخنی پلاؤ', category: 'Rice', price: 340 },
  { id: 'lassi', name: 'Fresh Lassi', nameUrdu: 'لسی', category: 'Drinks', price: 180 },
  { id: 'chai', name: 'Doodh Patti', nameUrdu: 'دودھ پتی', category: 'Drinks', price: 80 },
  { id: 'raita', name: 'Raita', nameUrdu: 'رائتہ', category: 'Sides', price: 90 },
  { id: 'salad', name: 'Kachumber', nameUrdu: 'کچومر', category: 'Sides', price: 70 },
];

export const DEFAULT_FLOOR = [
  { id: 'T1', x: 8, y: 24, w: 124, h: 124, shape: 'round' as const },
  { id: 'T2', x: 8, y: 48, w: 124, h: 124, shape: 'round' as const },
  { id: 'T3', x: 8, y: 72, w: 124, h: 124, shape: 'round' as const },
  { id: 'T4', x: 28, y: 26, w: 128, h: 128, shape: 'round' as const },
  { id: 'T5', x: 46, y: 26, w: 128, h: 128, shape: 'round' as const },
  { id: 'T6', x: 64, y: 26, w: 128, h: 128, shape: 'round' as const },
  { id: 'T7', x: 28, y: 52, w: 128, h: 128, shape: 'round' as const },
  { id: 'T8', x: 46, y: 52, w: 128, h: 128, shape: 'round' as const },
  { id: 'T9', x: 64, y: 52, w: 128, h: 128, shape: 'round' as const },
  { id: 'T10', x: 84, y: 24, w: 132, h: 132, shape: 'round' as const },
  { id: 'T11', x: 84, y: 48, w: 132, h: 132, shape: 'round' as const },
  { id: 'T12', x: 84, y: 72, w: 132, h: 132, shape: 'round' as const },
  { id: 'counter', x: 50, y: 90, w: 128, h: 36, shape: 'rect' as const, kind: 'counter' as const },
];
